# Generated by Django 5.0.8 on 2024-08-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_decription_servicepage_description'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='service_bg_image',
            field=models.ForeignKey(blank=True, help_text='This image will be used as background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
