# Generated by Django 5.0.8 on 2024-08-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_service_bg_image_servicepage_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='background_image',
            new_name='service_bg_image',
        ),
    ]
