# Generated by Django 5.0.8 on 2024-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_background_image_servicepage_service_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='description_short',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
