# Generated by Django 5.0.8 on 2024-08-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_background_image_homepage_button_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_background_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_background_video',
            field=models.ForeignKey(help_text='The banner background video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
