# Generated by Django 5.0.8 on 2024-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_banner_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_background_video',
            field=models.FileField(blank=True, help_text='The banner background video', null=True, upload_to='videos/'),
        ),
    ]
