# Generated by Django 5.0.8 on 2024-08-23 16:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('title', 1), ('cards', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Blod title text for the card. Max legth pf 100 charcters.', 'max_length': 100}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Blod title text for the card. Max legth pf 100 charcters.', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('cards', 5)]], {})}, null=True),
        ),
    ]
