# Generated by Django 5.0.8 on 2024-08-24 10:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('title', 1), ('cards', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bold title text for the card. Max length of 100 characters.', 'max_length': 100}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional text for the card. Max length of 255 characters.', 'max_length': 255, 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image will be automatically cropped to 570px by 370px'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'More details', 'max_length': 50}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('link_text', 5), ('internal_page', 6), ('external_page', 7)]], {'help_text': 'Enter your link details here.'}), 9: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('image', 4), ('links', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('cards', 10)]], {})}, null=True),
        ),
    ]
