# Generated by Django 5.0.8 on 2024-08-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='body',
        ),
    ]
