# Generated by Django 5.0.8 on 2024-08-26 18:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_flexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.StreamField([('title', 1), ('cards', 11), ('image_and_text_block', 17), ('call_to_action_block', 19), ('testimonals', 20), ('pricing_table', 21), ('richtext', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bold title text for the card. Max length of 100 characters.', 'max_length': 100}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional text for the card. Max length of 255 characters.', 'max_length': 255, 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image will be automatically cropped to 570px by 370px'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'More details', 'max_length': 50}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('link_text', 5), ('internal_page', 6), ('external_page', 7)]], {'help_text': 'Enter your link details here.'}), 9: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('image', 4), ('link', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('cards', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image will be cropped to 786px by 552px'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image to the left'), ('right', 'Image to the right')], 'help_text': 'Image on the left with text on the right. Or image  on the right with text on the left'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Max length 60 characters', 'max_length': 60}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Description upto 140 charaters', 'max_length': 140, 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('link_text', 5), ('internal_page', 6), ('external_page', 7)]], {}), 17: ('wagtail.blocks.StructBlock', [[('image', 12), ('image_alignment', 13), ('title', 14), ('text', 15), ('link', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'max length of 200', 'max_length': 200, 'null': True}), 19: ('wagtail.blocks.StructBlock', [[('title', 18), ('link', 16)]], {}), 20: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'testimonials.Testimonial', 'template': 'streams/testimonial_block.html'}), 21: ('streams.blocks.PricingTableBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Enter the title for richtext upto 200 characters', 'max_length': 200, 'null': True, 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('content', 23)]], {})}, null=True),
        ),
    ]
