# Generated by Django 5.0.8 on 2024-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_footerctasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerctasettings',
            name='button_external_page',
            field=models.URLField(blank=True, help_text='Enter the link to external page.(either internal or external page allowed)', null=True),
        ),
    ]
